#!/usr/bin/env python3
"""
compile_rule_frontmatter.py — the rule-band compiler.

The numeric prefix of a rule file IS its load-tier declaration:

    01-14  always_on       managed (regenerated by the bootstrap)
    15-19  always_on       repo-custom (never regenerated)
    20-34  glob            managed — MUST declare `paths:`
    35-39  glob            repo-custom — MUST declare `paths:`
    40-44  model_decision  managed
    45-59  model_decision  repo-custom

Authored keys: `description` (all rules), `paths` (glob bands only).
Derived keys: `name` (filename), `trigger` (band), `glob` (joined paths).

Prefixes 03 and 11 are permanently retired: they were the two historical
collision magnets, and any file carrying them marks a pre-overhaul tree.

Two kinds of finding, kept apart on purpose:

  BLOCKING   decidable from the text — a missing band, a duplicate prefix, a
             glob rule with no paths. These exit 1.
  ADVISORY   heuristics, in `rule_advisories.py` — description quality, unfilled
             placeholders, unresolvable skills, enforcement claims. These print
             and never fail, because a heuristic that blocks from day one turns
             its first false positive into an argument about the checker
             instead of an argument about the guidance.

Modes:
    --check     validate; exit 1 on any blocking violation (wired into pre-commit)
    --write     rewrite derived keys in place from the authored ones
    --advisory  report the heuristic findings only; never exits non-zero
"""

import json
import os
import re
import subprocess
import sys
from pathlib import Path

_HOOKS_DIR = os.path.abspath(os.path.dirname(__file__))
if _HOOKS_DIR not in sys.path:
    sys.path.insert(0, _HOOKS_DIR)
try:
    from rule_advisories import advisories_for_rule, check_layering, skill_search_dirs
except ImportError:  # pragma: no cover - advisories are optional, never fatal
    advisories_for_rule = check_layering = skill_search_dirs = None

_ROOT = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                       capture_output=True, text=True).stdout.strip()
if _ROOT:
    os.chdir(_ROOT)

#: Files that orient an agent but must not restate a rule (see check_layering).
ORIENTATION_FILES = ("AGENTS.md", "CLAUDE.md", "GEMINI.md")

RULES_DIR = Path(".agents/rules")
MANIFEST = Path(".agents/rules-manifest.json")
RETIRED_PREFIXES = {3, 11}

BANDS = (
    (1, 14, "always_on", "managed"),
    (15, 19, "always_on", "custom"),
    (20, 34, "glob", "managed"),
    (35, 39, "glob", "custom"),
    (40, 44, "model_decision", "managed"),
    (45, 59, "model_decision", "custom"),
)


def band_of(number: int):
    for lo, hi, trigger, ownership in BANDS:
        if lo <= number <= hi:
            return trigger, ownership
    return None, None


def parse_frontmatter(text: str):
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        return {}, None
    fm, keys = m.group(1), {}
    current = None
    for line in fm.splitlines():
        kv = re.match(r"^([A-Za-z_]+):\s*(.*)$", line)
        if kv:
            current = kv.group(1)
            value = kv.group(2).strip().strip("\"'")
            keys[current] = [] if value == "" else value
        elif re.match(r"^\s+-\s+", line) and isinstance(keys.get(current), list):
            keys[current].append(line.split("-", 1)[1].strip().strip("\"'"))
    return keys, m


def derived_frontmatter(path: Path, keys: dict, trigger: str) -> str:
    stem = re.sub(r"^\d{2}-", "", path.stem.removesuffix("-rules"))
    lines = [f"name: {stem}"]
    description = keys.get("description")
    if description:
        lines.append(f"description: {description}")
    lines.append(f"trigger: {trigger}")
    paths = keys.get("paths") or []
    if paths:
        lines.append("glob: \"" + ",".join(paths) + "\"")
        lines.append("paths:")
        lines += [f"  - \"{p}\"" for p in paths]
    return "---\n" + "\n".join(lines) + "\n---\n"


def check_rule(path: Path, manifest: dict, errors: list):
    m = re.match(r"^(\d{2})-", path.name)
    if not m:
        errors.append(f"{path.name}: no numeric prefix — every rule declares "
                      "its load tier through its number")
        return None
    number = int(m.group(1))
    if number in RETIRED_PREFIXES:
        errors.append(f"{path.name}: prefix {number:02d} is permanently "
                      "retired; renumber into the correct band")
        return None
    trigger, ownership = band_of(number)
    if trigger is None:
        errors.append(f"{path.name}: prefix {number:02d} is outside every "
                      "band (01-14, 15-19, 20-34, 35-39, 40-44, 45-59)")
        return None
    keys, _ = parse_frontmatter(path.read_text(errors="ignore"))
    if not keys.get("description"):
        errors.append(f"{path.name}: missing description: — a rule without "
                      "one is not lazily loaded, it is undiscoverable")
    paths_declared = bool(keys.get("paths"))
    if trigger == "glob" and not paths_declared:
        errors.append(f"{path.name}: glob-band rule declares no paths: — "
                      "its scope can never fire")
    if trigger != "glob" and paths_declared:
        errors.append(f"{path.name}: paths: declared outside the glob band — "
                      "the scope can never be consulted")
    if ownership == "managed" and manifest and path.name not in manifest:
        errors.append(
            f"{path.name}: hand-authored file in MANAGED band space "
            f"({trigger} managed). It will be overwritten or deleted by the "
            "next --update. Renumber to 15-19, 35-39 or 45-59.")
    return number, trigger, keys


def report_advisories() -> None:
    """Print the heuristic findings. Never fails: see the module docstring."""
    if advisories_for_rule is None:
        return
    search_dirs = skill_search_dirs()
    findings = []
    for path in sorted(RULES_DIR.glob("*.md")):
        if path.is_symlink():
            continue
        text = path.read_text(errors="ignore")
        keys, match = parse_frontmatter(text)
        body = text[match.end():] if match else text
        stem = re.sub(r"^\d{2}-", "", path.stem.removesuffix("-rules"))
        description = keys.get("description")
        if not isinstance(description, str):
            description = ""
        findings += [(path, msg) for msg in
                     advisories_for_rule(stem, description, body, search_dirs)]
    orientation = [Path(name) for name in ORIENTATION_FILES]
    findings += check_layering(orientation)
    if not findings:
        return
    print("Rule advisories ({}) — reported, not blocking:".format(len(findings)))
    for path, message in findings:
        print("  {}: {}".format(path, message))


def main():
    if "--advisory" in sys.argv:
        if RULES_DIR.is_dir():
            report_advisories()
        return 0
    mode = "--check" if "--check" in sys.argv else (
        "--write" if "--write" in sys.argv else "--check")
    if not RULES_DIR.is_dir():
        return 0
    manifest = {}
    if MANIFEST.exists():
        try:
            manifest = json.loads(MANIFEST.read_text()).get("rules", {})
        except (ValueError, OSError):
            pass
    errors, seen = [], {}
    for path in sorted(RULES_DIR.glob("*.md")):
        if path.is_symlink():
            continue
        result = check_rule(path, manifest, errors)
        if not result:
            continue
        number, trigger, keys = result
        if number in seen:
            errors.append(f"{path.name}: duplicate numeric prefix with "
                          f"{seen[number]} — no multi-file slots exist")
        seen[number] = path.name
        if mode == "--write":
            text = path.read_text(errors="ignore")
            keys, m = parse_frontmatter(text)
            new_fm = derived_frontmatter(path, keys, trigger)
            body = text[m.end():] if m else text
            path.write_text(new_fm + body)
    if errors:
        print("Rule frontmatter compile FAILED:", file=sys.stderr)
        for err in errors:
            print(f"  - {err}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
