#!/usr/bin/env python3
"""
compile_aiignore.py

Translates `.aiignore` into the exclusion mechanism each agent platform actually
honours. No platform reads `.aiignore` itself — this is what makes it real.

Verified platform behaviour (do not "simplify" this by writing one file):
  * Antigravity / ripgrep-based search  -> `.ignore` (a real, honoured filename)
  * Claude Code                         -> permissions.deny "Read(./glob)" rules
                                           in .claude/settings.json
  * OpenCode                            -> permission.read/glob/grep deny map
                                           in opencode.json
  * GitHub Copilot                      -> org-level content exclusion, applied
                                           server side; a repo file cannot do it,
                                           so we emit a paste-ready list

This edits files it does not own, so two rules are absolute:

  1. NEVER write over a file that could not be parsed. A syntax error means the
     content is unknown, and overwriting it would silently delete whatever was
     there — including the security hooks in .claude/settings.json.
  2. NEVER remove an entry this compiler did not create. What it generated last
     time is recorded in a side manifest, and only those entries are replaced,
     so a hand-written deny rule survives every recompile.

The manifest is a side file rather than a key inside the platform configs
because those configs are schema-validated — OpenCode rejects unknown keys
inside its `lsp` object, and the same risk applies elsewhere.

Modes:
  (default)  regenerate every derived target
  --check    exit non-zero if any derived target is out of date (pre-commit)
"""

import json
import os
import subprocess
import sys
from pathlib import Path

AIIGNORE = ".aiignore"
IGNORE_FILE = ".ignore"
CLAUDE_SETTINGS = ".claude/settings.json"
OPENCODE_CONFIG = "opencode.json"
COPILOT_EXCLUSION = ".github/copilot-content-exclusion.yml"
MANIFEST = ".agents/aiignore-generated.json"

GENERATED_HEADER = (
    "# GENERATED FROM .aiignore by .agents/hooks/compile_aiignore.py\n"
    "# Do not edit this file directly — edit .aiignore and re-run the compiler.\n"
)

_ROOT = subprocess.run(
    ["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True
).stdout.strip()
if _ROOT:
    os.chdir(_ROOT)


class ConfigUnreadable(Exception):
    """A file exists but could not be parsed — refuse to touch it."""


def read_patterns():
    """Return (all_lines, positive_patterns). Negations stay in .ignore, where
    they are meaningful, but are not turned into deny rules — a deny list has no
    way to express 'except this'."""
    try:
        lines = Path(AIIGNORE).read_text(encoding="utf-8").splitlines()
    except OSError:
        return None, []
    patterns = []
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith("!"):
            continue
        patterns.append(stripped)
    return lines, patterns


def to_glob(pattern: str) -> str:
    """Convert a gitignore pattern to a glob usable in deny rules.

    gitignore semantics matter here: a pattern without a leading slash matches
    at ANY depth, so `*.pem` must become `**/*.pem`. Compiling it to `*.pem`
    would silently protect only the repository root.
    """
    raw = pattern.strip()
    anchored = raw.startswith("/")
    p = raw.lstrip("/").rstrip("/")
    if raw.rstrip("/") != raw or raw.endswith("/"):
        p = p + "/**"
    if not anchored and not p.startswith("**/"):
        p = "**/" + p
    return p


def load_json(path):
    """Parse a JSON file.

    A missing file is an empty starting point. A file that exists but does not
    parse is a hard error: returning {} here would hand an empty config to the
    renderer, and the result would be written straight over the user's file.
    """
    try:
        text = Path(path).read_text(encoding="utf-8")
    except OSError:
        return {}
    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:
        raise ConfigUnreadable(
            "{}: {} (line {}, column {})".format(path, exc.msg, exc.lineno, exc.colno)
        ) from exc


def dump_json(data) -> str:
    text = json.dumps(data, indent=2) + "\n"
    try:
        res = subprocess.run(
            ["npx", "--no-install", "prettier", "--stdin-filepath", "config.json"],
            input=text,
            capture_output=True,
            text=True,
        )
        if res.returncode == 0 and res.stdout:
            return res.stdout
    except Exception as err:
        sys.stderr.write(f"Prettier fallback: {err}\n")
    return text


def render_ignore(lines) -> str:
    return GENERATED_HEADER + "\n".join(lines) + "\n"


def render_claude(patterns, existing, previous):
    """Replace only the deny rules this compiler generated last time."""
    settings = json.loads(json.dumps(existing)) if existing else {}
    permissions = settings.setdefault("permissions", {})
    generated = ["Read(./{})".format(to_glob(p)) for p in patterns]

    stale = set(previous)
    kept = [d for d in permissions.get("deny", []) if d not in stale]
    for rule in generated:
        if rule not in kept:
            kept.append(rule)
    permissions["deny"] = kept
    return settings, generated


def render_opencode(patterns, existing, previous):
    """OpenCode evaluates permission rules with LAST MATCHING RULE WINNING, so
    the catch-all must come first and the deny rules last. Emitting `**: allow`
    after the denies would silently cancel every one of them."""
    config = json.loads(json.dumps(existing)) if existing else {}
    permission = config.setdefault("permission", {})
    rules = {to_glob(p): "deny" for p in patterns}
    stale = set(previous)

    for tool in ("read", "glob", "grep"):
        current = permission.get(tool)
        if current is not None and not isinstance(current, dict):
            # A scalar ("ask" / "deny") is a deliberate repository-wide posture.
            # Replacing it with an allow-by-default map would weaken it.
            print("NOTE: permission.{} is {!r}; left unchanged so the existing "
                  "posture is not weakened.".format(tool, current))
            continue
        merged = {"**": "allow"}
        if isinstance(current, dict):
            merged.update({k: v for k, v in current.items()
                           if k not in rules and k != "**" and k not in stale})
        merged.update(rules)
        permission[tool] = merged
    return config, sorted(rules)


def render_copilot(patterns) -> str:
    entries = "\n".join('  - "/{}"'.format(to_glob(p)) for p in patterns)
    return (
        "# GENERATED FROM .aiignore by .agents/hooks/compile_aiignore.py\n"
        "#\n"
        "# GitHub Copilot content exclusion is applied SERVER SIDE and cannot be\n"
        "# configured by a file in the repository. Paste the block below into:\n"
        "#   GitHub -> Organization (or Repository) Settings -> Copilot ->\n"
        "#   Content exclusion\n"
        "#\n"
        "# Until that is done, Copilot will still read these paths.\n"
        "\n"
        '"*":\n' + entries + "\n"
    )


def main():
    check_only = "--check" in sys.argv
    lines, patterns = read_patterns()
    if lines is None:
        if not check_only:
            print("No {} found; nothing to compile.".format(AIIGNORE))
        return

    try:
        manifest = load_json(MANIFEST)
        claude_settings, claude_generated = render_claude(
            patterns, load_json(CLAUDE_SETTINGS), manifest.get("claude_deny", []))
        opencode_config, opencode_generated = render_opencode(
            patterns, load_json(OPENCODE_CONFIG), manifest.get("opencode_rules", []))
    except ConfigUnreadable as exc:
        print("=" * 78)
        print("AI EXCLUSION COMPILER ABORTED — a config file could not be parsed")
        print("  {}".format(exc))
        print("")
        print("  Nothing was written. That file is left exactly as it is, because")
        print("  overwriting a config we cannot read would delete whatever it")
        print("  contains, including the agent hooks.")
        print("  Fix the JSON syntax, then re-run.")
        print("=" * 78)
        sys.exit(1)

    targets = {
        IGNORE_FILE: render_ignore(lines),
        CLAUDE_SETTINGS: dump_json(claude_settings),
        OPENCODE_CONFIG: dump_json(opencode_config),
        COPILOT_EXCLUSION: render_copilot(patterns),
        MANIFEST: dump_json({
            "comment": ("Records what compile_aiignore.py generated, so the next "
                        "run replaces only its own entries and leaves "
                        "hand-written rules alone. Do not edit."),
            "claude_deny": claude_generated,
            "opencode_rules": opencode_generated,
        }),
    }

    stale = []
    for path, content in targets.items():
        try:
            current = Path(path).read_text(encoding="utf-8")
        except OSError:
            current = None
        if current == content:
            continue
        stale.append(path)
        if not check_only:
            Path(path).parent.mkdir(parents=True, exist_ok=True)
            Path(path).write_text(content, encoding="utf-8")

    if check_only and stale:
        print("=" * 78)
        print("AI EXCLUSION OUT OF DATE")
        print("  .aiignore has changed but these derived targets were not regenerated:")
        for path in stale:
            print("    - {}".format(path))
        print("")
        print("  Run:  python3 .agents/hooks/compile_aiignore.py")
        print("  then stage the regenerated files.")
        print("=" * 78)
        sys.exit(1)

    if not check_only:
        if stale:
            print("Compiled {} -> {} pattern(s) into:".format(AIIGNORE, len(patterns)))
            for path in stale:
                print("  updated {}".format(path))
            print("NOTE: Copilot exclusion is server side — paste {} into the "
                  "GitHub Copilot content-exclusion settings."
                  .format(COPILOT_EXCLUSION))
        else:
            print("AI exclusion targets already up to date.")


if __name__ == "__main__":
    main()
