#!/usr/bin/env python3
"""
copilot_index.py

The Copilot rule index — read, rebuild and verify — with `.agents/rules/` as
the single source of truth.

Copilot has no rule-directory convention of its own: `.github/copilot-instructions.md`
is the only place it learns which rules exist, and it learns them from a list of
markdown links. That list was rendered once, at bootstrap time, from the rules
*that run produced* — so a repo-owned rule (bands 15-19/35-39/45-59) or any rule
added afterwards never reached Copilot at all, and nothing noticed, because the
parity audit only ever checked that a listed rule exists and never that an
existing rule is listed.

This module owns both directions:

  * `listed_rules()` / `canonical_rules()` — the two sets the audit compares.
  * `refresh_text()` — rebuild the index block from the rules on disk, so the
    sync script can bring a stale file back into line without a re-bootstrap.

Run it directly as the pre-commit gate (`--check`) or as the refresher (no
arguments). `scripts/sync_agentic_configs.sh` calls the refresher.
"""

import re
import sys
from pathlib import Path

INDEX_REL = ".github/copilot-instructions.md"
RULES_REL = ".agents/rules"
HEADING = "## Rule Index"

# The link form the index template emits. Matched rather than assumed so a
# hand-widened index (extra prose after the link) still parses.
_LINK_RE = re.compile(r"\]\(\.\./\.agents/rules/([\w.-]+\.md)\)")


def canonical_rules(repo: Path) -> set:
    """Every rule file the repository actually has.

    Symlinks are skipped: `.claude/rules` and `.opencode/rules` mirror this
    directory, and a mirror that leaked back in would be counted twice.
    """
    rules_dir = repo / RULES_REL
    if not rules_dir.is_dir():
        return set()
    return {p.name for p in rules_dir.glob("*.md") if not p.is_symlink()}


def listed_rules(text: str) -> set:
    """Every rule the Copilot index points at."""
    return set(_LINK_RE.findall(text))


def rule_label(filename: str) -> str:
    return filename.removesuffix(".md").removesuffix("-rules")


def index_lines(filenames) -> list:
    return [f"- [{rule_label(name)}](../{RULES_REL}/{name})"
            for name in sorted(filenames)]


def _block_bounds(lines: list) -> tuple:
    """(start, end) of the index list body, or (-1, -1) when there is none.

    `start` is the first line after the heading; `end` is exclusive and stops
    at the first line that is neither blank nor a rule link — the "Hard
    constraints" paragraph that follows the list in the generated file.
    """
    try:
        head = lines.index(HEADING)
    except ValueError:
        return -1, -1
    start = head + 1
    end = start
    for i in range(start, len(lines)):
        line = lines[i]
        if not line.strip() or _LINK_RE.search(line):
            end = i + 1
            continue
        break
    # Trim trailing blank lines back out of the block so the rebuild does not
    # accumulate one blank line per run.
    while end > start and not lines[end - 1].strip():
        end -= 1
    return start, end


def refresh_text(text: str, filenames) -> str:
    """Return `text` with its rule index replaced by `filenames`.

    An index with no `## Rule Index` heading is a file this generator does not
    recognise — a hand-written Copilot instruction sheet, for instance. Its
    content is never rewritten; the section is appended instead, so Copilot
    gains the rules without the repository losing its prose.
    """
    lines = text.splitlines()
    body = [""] + index_lines(filenames)
    start, end = _block_bounds(lines)
    if start < 0:
        tail = lines + ([""] if lines and lines[-1].strip() else [])
        return "\n".join(tail + [HEADING] + body).rstrip("\n") + "\n"
    tail = lines[end:]
    # One blank line separates the list from whatever follows — added only when
    # the tail does not already start with one, or every run gains a line.
    if tail and tail[0].strip():
        body.append("")
    rebuilt = lines[:start] + body + tail
    return "\n".join(rebuilt).rstrip("\n") + "\n"


def _default_index(filenames) -> str:
    """A minimal index for a repository that has none yet. The bootstrap writes
    a fuller pointer file; this exists so the refresher is never the reason a
    repository has no Copilot entry point at all."""
    return refresh_text(
        "<!-- @generated by the agentic bootstrap from .agents/rules/. -->\n\n"
        "# GitHub Copilot Repository Instructions\n\n"
        "The single source of truth for agent behavior is "
        "[AGENTS.md](../AGENTS.md) plus the numbered rule files in "
        "[.agents/rules/](../.agents/rules/).\n",
        filenames)


def check(repo: Path) -> list:
    """Problems with the index, as human-readable lines. Empty means healthy."""
    canonical = canonical_rules(repo)
    if not canonical:
        return []
    index = repo / INDEX_REL
    if not index.exists():
        return [f"{INDEX_REL} is missing — Copilot has no rule index at all"]
    listed = listed_rules(index.read_text(encoding="utf-8", errors="ignore"))
    problems = [f"{INDEX_REL} does not list {name} — Copilot never sees this rule"
                for name in sorted(canonical - listed)]
    problems += [f"{INDEX_REL} links {name}, which does not exist"
                 for name in sorted(listed - canonical)]
    return problems


def refresh(repo: Path) -> bool:
    """Rewrite the index from `.agents/rules/`. True when the file changed."""
    canonical = canonical_rules(repo)
    if not canonical:
        return False
    index = repo / INDEX_REL
    if index.exists():
        current = index.read_text(encoding="utf-8", errors="ignore")
        updated = refresh_text(current, canonical)
    else:
        current, updated = "", _default_index(canonical)
    if updated == current:
        return False
    index.parent.mkdir(parents=True, exist_ok=True)
    index.write_text(updated, encoding="utf-8")
    return True


def main() -> int:
    args = [a for a in sys.argv[1:] if a != "--check"]
    repo = Path(args[0]) if args else Path(".")
    if "--check" in sys.argv[1:]:
        problems = check(repo)
        for problem in problems:
            print(f"[X] {problem}")
        if problems:
            print("    Run: python3 .agents/hooks/copilot_index.py")
            return 1
        return 0
    if refresh(repo):
        print(f"Refreshed {INDEX_REL} from {RULES_REL}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
