#!/usr/bin/env python3
"""
file_size_scope.py

Which files the file-size budget covers, and why any one of them is exempt.

This is the CLASSIFICATION third of the ratchet. `file_size_baseline.py` holds
its state, `check_file_size_budget.py` its command-line surface, and this file
decides what is in scope at all. The three change for entirely different
reasons: this one when the repository's idea of "not ours to decompose"
changes, the others when the bookkeeping or the CLI does.

WHAT WENT WRONG BEFORE (upstream TT-1399). The vendor test was a bare substring
match: any file whose first 4000 bytes contained a vendor name ANYWHERE — in a
comment, in a string, or in a constant that merely lists the names — dropped
out of the budget silently. A 500-line first-party file whose first line was a
three-letter vendor name in a comment was not measured at all, while an
identical file without it was. Worse, the ratchet's own source listed every
vendor name it knows, so once it grew past 400 lines it exempted ITSELF from
the budget it enforces. An audit of the whole tree under the old rule found
exactly one file the vendor branch had ever exempted: the gate.

WHAT IS DIFFERENT NOW. Every content-based exemption needs TWO independent
signals, not one. A vendor name only counts on a line that is also shaped like
a copyright notice: it carries a notice word or symbol AND an ownership claim
(a year, or "all rights reserved"). A generated marker only counts inside a
directory that is plausibly generated output — which the generated branch
already required, and which is the shape the vendor rule now mirrors.

Requiring a notice rather than a path is deliberate. Vendored code arrives
inside otherwise first-party directories, so gating the content test on path as
well would leave it able to fire almost nowhere, and EXCLUDED_PREFIXES already
covers the vendored trees that do sit at a recognisable path. A first-party
file cannot honestly carry another company's copyright notice, so the notice is
the corroboration.

Every decision this module makes is REPORTABLE, not just a boolean: callers get
an `Exemption` naming the kind and the reason, so a file that was never
measured can be told apart from one that was measured and passed. That
distinction is the other half of the fix — the old `--report` output said
"unchecked suffix" for a `.py` file whose suffix was perfectly fine.
"""

from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass

HEAD_BYTES = 4000

# Rendered from the detected stacks. Hardcoding `(".py",)` here made the
# file-size rule completely inert in every C and C++ repository the bootstrap
# ever touched: the hook ran, found nothing it recognised, and reported success.
CHECKED_SUFFIXES: tuple[str, ...] = (
    '.cc',
    '.cpp',
    '.cxx',
    '.h',
    '.hpp',
    '.py',
)
EXCLUDED_PREFIXES: tuple[str, ...] = (
    '.agents/',
    'build/',
    'tests/',
    'test/',
)
#: Matched anywhere in the path, for vendored trees nested inside the project.
EXCLUDED_FRAGMENTS: tuple[str, ...] = ()

#: Third-party names. A name alone proves nothing — see VENDOR_NOTICE_WORD.
VENDOR_NAMES: tuple[bytes, ...] = (
    b'nxp',
    b'freescale',
    b'arm limited',
    b'st microelectronics',
    b'stmicroelectronics',
    b'texas instruments',
    b'microchip',
    b'silicon laboratories',
    b'nordic semiconductor',
    b'the qt company',
    b'cmsis',
)

# The two signals a line must carry before a vendor name on it counts as a
# third-party copyright notice. Both are needed: the word on its own appears in
# ordinary prose and in identifiers, and a bare year appears in every changelog.
VENDOR_NOTICE_WORD = re.compile(rb"copyright|\(c\)|\xc2\xa9")
VENDOR_NOTICE_CLAIM = re.compile(rb"\b(19|20)\d{2}\b|all rights reserved")

GENERATED_MARKERS = (
    b"@generated", b"do not edit", b"do not modify", b"automatically generated",
    b"auto-generated", b"autogenerated", b"generated by",
)

# A marker alone cannot exempt a file. The exemption exists for vendored and
# machine-generated trees; if one comment were sufficient, an agent that has
# read the rule could opt out of the budget in a single line — and the rule
# text tells it exactly which line. So a marker only counts inside a location
# that is plausibly not ours.
GENERATED_LOCATION = re.compile(
    r"(^|/)(vendor|third_party|node_modules|generated|gen|__generated__|"
    r"autogen|golden|goldens|snapshots|__snapshots__|baseline|baselines|"
    r"externals?|deps|_deps|dist|build|proto|protos|sdk)(/|$)")

# The generated trees THIS repository has, from the same detector the budget
# exclusion and the pre-commit style exclusion read. A name list can only ever
# cover the universal conventions; `src/proto_gen/` is generated output under a
# name no list would guess, and only the detector knows that.
GENERATED_PREFIXES: tuple[str, ...] = ()


@dataclass(frozen=True)
class Exemption:
    """Why a file is outside the budget, in a form a report can print."""

    kind: str
    detail: str

    def __str__(self) -> str:
        return "{} — {}".format(self.kind, self.detail)

    @property
    def content_addressed(self) -> bool:
        """Whether this verdict came from the file's bytes rather than its path.

        A path-shaped exemption is visible in any listing; a content-addressed
        one is invisible unless something says it out loud, which is the failure
        this module was rewritten to prevent.
        """
        return self.kind in ("vendored", "generated")


def read_head(path: str, staged: bool = False) -> bytes:
    """The first HEAD_BYTES of the content actually being judged."""
    if staged:
        result = subprocess.run(["git", "show", ":{}".format(path)],
                                capture_output=True)
        return result.stdout[:HEAD_BYTES] if result.returncode == 0 else b""
    try:
        with open(path, "rb") as handle:
            return handle.read(HEAD_BYTES)
    except OSError:
        return b""


def _unchecked_suffix(path: str, extra_excludes) -> Exemption | None:
    if CHECKED_SUFFIXES and path.endswith(CHECKED_SUFFIXES):
        return None
    return Exemption(
        "unchecked-suffix",
        "the budget covers {} only".format(", ".join(CHECKED_SUFFIXES)))


def _excluded_prefix(path: str, extra_excludes) -> Exemption | None:
    for prefix in EXCLUDED_PREFIXES:
        if path.startswith(prefix):
            return Exemption("excluded-path",
                             "under the excluded prefix '{}'".format(prefix))
    return None


def _excluded_fragment(path: str, extra_excludes) -> Exemption | None:
    for fragment in EXCLUDED_FRAGMENTS:
        if fragment and fragment in path:
            return Exemption("excluded-path",
                             "matches the excluded fragment '{}'".format(fragment))
    return None


def _baseline_exclude(path: str, extra_excludes) -> Exemption | None:
    for fragment in extra_excludes:
        if fragment and fragment in path:
            return Exemption(
                "excluded-path",
                "matches '{}' in the baseline's exclude list".format(fragment))
    return None


def _vendor_copyright(path: str, head: bytes) -> Exemption | None:
    """A third-party copyright notice: self-evidently not ours to refactor.

    The name must sit on a line that IS a notice, not merely a line that names
    a company. That corroboration is the whole fix; without it any mention
    anywhere in the head was enough, including this module's own list.
    """
    for line in head.splitlines():
        if not (VENDOR_NOTICE_WORD.search(line) and VENDOR_NOTICE_CLAIM.search(line)):
            continue
        for name in VENDOR_NAMES:
            if name in line:
                return Exemption(
                    "vendored",
                    "third-party copyright notice for '{}'".format(name.decode()))
    return None


def _in_generated_location(path: str) -> bool:
    return bool(GENERATED_LOCATION.search(path)) or path.startswith(
        GENERATED_PREFIXES)


def _generated_output(path: str, head: bytes) -> Exemption | None:
    for marker in GENERATED_MARKERS:
        if marker in head and _in_generated_location(path):
            return Exemption(
                "generated",
                "'{}' marker in a generated location".format(marker.decode()))
    return None


# Ordered registries rather than a chain of ifs: a further exemption is an entry
# here, testable on its own, and the reporting side needs no edit at all. Path
# rules run first because they are free — the content rules need the file's
# bytes, which under --staged means a subprocess per file.
PATH_RULES = (_unchecked_suffix, _excluded_prefix, _excluded_fragment,
              _baseline_exclude)
CONTENT_RULES = (_vendor_copyright, _generated_output)


def exemption_for(path: str, extra_excludes=(), staged: bool = False):
    """Why `path` is outside the file-size budget, or None if it is covered."""
    for rule in PATH_RULES:
        verdict = rule(path, extra_excludes)
        if verdict is not None:
            return verdict
    head = read_head(path, staged).lower()
    if not head:
        return None
    for rule in CONTENT_RULES:
        verdict = rule(path, head)
        if verdict is not None:
            return verdict
    return None


def is_checked(path: str, extra_excludes=(), staged: bool = False) -> bool:
    """Whether the file-size budget applies to `path`."""
    return exemption_for(path, extra_excludes, staged) is None
