@startuml
package "print_operation" {
  FffGCodeWriter *-- "1" PrintPlan

  abstract class PrintOperation {
    {abstract} write(PathExporter)
    applyProcessors()
  }

  abstract PrintOperationSequence
  abstract ExtruderMove

  PrintOperationSequence -left-|> PrintOperation
  PrintOperationSequence *-- "*" PrintOperation

  LayerPlan -up-|> PrintOperationSequence
  ExtruderPlan -up-|> PrintOperationSequence
  ContinuousExtruderMoveSequence -up-|> PrintOperationSequence
  PrintPlan -up-|> PrintOperationSequence
  MeshFeatureExtrusion -up-|> FeatureExtrusion

  ExtruderMove -up-|> PrintOperation
  ExtrusionMove -up-|> ExtruderMove
  TravelMove -up-|> ExtruderMove

  class SetNozzleTemperatureCommand #paleturquoise
  SetNozzleTemperatureCommand -up-|> PrintOperation
  class SetCoolingFanCommand #paleturquoise
  SetCoolingFanCommand -up-|> PrintOperation

  FeatureExtrusion -up-|> PrintOperationSequence
  TravelRoute -up-|> ContinuousExtruderMoveSequence
}
package "plan_export" {
  abstract PlanExporter {
      {abstract} void writeExtrusionMove(...)
      {abstract} void writeTravelMove(...)
      {abstract} void writeSetNozzleTemperature(...)
      {abstract} void writeSetBedTemperature(...)
      {abstract} void writeSetCoolingFanSpeed(...)
  }

  GCodeExporter -up-|> PlanExporter
  CommunicationExporter -up-|> PlanExporter
  MultiExporter -right-|> PlanExporter
  ConsumptionEstimationExporter -up-|> PlanExporter
  ConsoleExporter -up-|> PlanExporter

  MultiExporter *-- "*" PlanExporter
}

ExtruderMove : Point end
ExtruderMove : double speed

ExtrusionMove : coord_t line_width
ExtrusionMove : coord_t line_height
ExtrusionMove : double flow

FeatureExtrusion : FeatureType type

MeshFeatureExtrusion : SliceMeshStorage mesh

ContinuousExtruderMoveSequence : bool closed
ContinuousExtruderMoveSequence : double speed_factor

package "operation_transformation" {
  abstract PrintOperationTransformer << template<class OperationType> >> {
    {abstract} void process(OperationType operation)
  }

  LayerPlanTravelMovesInserter -up-|> PrintOperationTransformer
  AddPrimeTowerTransformer -up-|> PrintOperationTransformer
  MinimumLayerTimeTransformer -up-|> PrintOperationTransformer
  CoastingTransformer -up-|> PrintOperationTransformer
  BackPressureCompensationTransformer -up-|> PrintOperationTransformer
  SplitterTransformer -up-|> PrintOperationTransformer
  AddNozzleTemperatureCommandsTransformer -up-|> InsertOperationOnTimeTransformer
  AddBedTemperatureCommandsTransformer -up-|> InsertOperationOnTimeTransformer
  AddCoolingFanCommandsTransformer -up-|> InsertOperationOnTimeTransformer
  InsertOperationOnTimeTransformer -up-|> PrintOperationTransformer

  LayerPlanTravelMovesInserter *-- "*" TravelMoveGenerator
  abstract TravelMoveGenerator
  DirectTravelMoveGenerator -up-|> TravelMoveGenerator
  CombingTravelMoveGenerator -up-|> TravelMoveGenerator

  BedAdhesionConstraintsGenerator -up-|> FeatureExtrusionsConstraintsGenerator
  MeshFeaturesConstraintsGenerator -up-|> FeatureExtrusionsConstraintsGenerator

  MonotonicConstraintsGenerator -up-|> MoveSequencesConstraintsGenerator

  ExtruderPlanScheduler -up-|> PrintOperationTransformer
  class FeatureExtrusionScheduler
  ExtruderPlanScheduler *-- "*" FeatureExtrusionScheduler
  FeatureExtrusionScheduler *-- "*" FeatureExtrusionsConstraintsGenerator
  FeatureExtrusionScheduler *-- "*" MoveSequencesConstraintsGenerator

  SplitterTransformer *-- "*" PathSplitter

  abstract PathSplitter
  GradualFlowSplitter -up-|> PathSplitter
  ScarfSeamSplitter -up-|> PathSplitter
  SmoothSpeedSplitter -up-|> PathSplitter

  class InsertOperationOnTimeTransformer #paleturquoise
  class AddNozzleTemperatureCommandsTransformer #paleturquoise
  class AddBedTemperatureCommandsTransformer #paleturquoise
  class AddCoolingFanCommandsTransformer #paleturquoise
  class AddPrimeTowerTransformer #paleturquoise
  class CombingTravelMoveGenerator #paleturquoise
  class MinimumLayerTimeTransformer #paleturquoise
  class CoastingTransformer #paleturquoise
  class BackPressureCompensationTransformer #paleturquoise
  class SplitterTransformer #paleturquoise
  class PathSplitter #paleturquoise
  class GradualFlowSplitter #paleturquoise
  class ScarfSeamSplitter #paleturquoise
  class SmoothSpeedSplitter #paleturquoise
}

package "feature_generation" {
  abstract FeatureGenerator

  MeshFeatureGenerator -up-|> FeatureGenerator
  NormalSupportGenerator -up-|> FeatureGenerator
  TreeSupportGenerator -up-|> FeatureGenerator
  OozeShieldGenerator -up-|> FeatureGenerator
  SkirtBrimGenerator -up-|> FeatureGenerator

  class FeatureGenerator #paleturquoise
  class MeshFeatureGenerator #paleturquoise
  class NormalSupportGenerator #paleturquoise
  class TreeSupportGenerator #paleturquoise
  class OozeShieldGenerator #paleturquoise
  class SkirtBrimGenerator #paleturquoise
}
@enduml
