@startuml
package "path_planning" {
  FffGCodeWriter *-- "1" LayerPlanBuffer

  abstract class PrintOperation {
    {abstract} write(PathExporter)
    applyProcessors()
  }

  abstract PrintOperationSequence
  abstract ExtruderMove

  PrintOperationSequence -left-|> PrintOperation
  PrintOperationSequence *-- "*" PrintOperation

  LayerPlan -up-|> PrintOperationSequence
  ExtruderPlan -up-|> PrintOperationSequence
  ContinuousExtruderMoveSequence -up-|> PrintOperationSequence
  LayerPlanBuffer -up-|> PrintOperationSequence
  MeshFeatureExtrusion -up-|> FeatureExtrusion

  ExtruderMove -up-|> PrintOperation
  ExtrusionMove -up-|> ExtruderMove
  TravelMove -up-|> ExtruderMove

  class SetNozzleTemperatureCommand #paleturquoise
  SetNozzleTemperatureCommand -up-|> PrintOperation
  class SetCoolingFanCommand #paleturquoise
  SetCoolingFanCommand -up-|> PrintOperation

  FeatureExtrusion -up-|> PrintOperationSequence
  TravelRoute -up-|> ContinuousExtruderMoveSequence
}
package "path_export" {
  abstract PathExporter {
      {abstract} void writeExtrusionMove(...)
      {abstract} void writeTravelMove(...)
      {abstract} void writeSetNozzleTemperature(...)
      {abstract} void writeSetBedTemperature(...)
      {abstract} void writeSetCoolingFanSpeed(...)
  }

  GCodeExporter -up-|> PathExporter
  CommunicationExporter -up-|> PathExporter
  MultiExporter -right-|> PathExporter
  ConsumptionEstimationExporter -up-|> PathExporter
  ConsoleExporter -up-|> PathExporter

  MultiExporter *-- "*" PathExporter
}

ExtruderMove : Point end
ExtruderMove : double speed

ExtrusionMove : coord_t line_width
ExtrusionMove : coord_t line_height
ExtrusionMove : double flow

FeatureExtrusion : FeatureType type

MeshFeatureExtrusion : SliceMeshStorage mesh

ContinuousExtruderMoveSequence : bool closed
ContinuousExtruderMoveSequence : double speed_factor

package "path_processing" {
  abstract PrintOperationProcessor << template<class OperationType> >> {
    {abstract} void process(OperationType operation)
  }

  AddLayerPlanTravelMovesProcessor -up-|> PrintOperationProcessor
  PrimeTowerProcessor -up-|> PrintOperationProcessor
  MinimumLayerTimeProcessor -up-|> PrintOperationProcessor
  CoastingProcessor -up-|> PrintOperationProcessor
  BackPressureCompensationProcessor -up-|> PrintOperationProcessor
  SplitterProcessor -up-|> PrintOperationProcessor
  NozzleTemperatureCommandsProcessor -up-|> InsertOperationOnTimeProcessor
  BedTemperatureCommandsProcessor -up-|> InsertOperationOnTimeProcessor
  CoolingFanCommandsProcessor -up-|> InsertOperationOnTimeProcessor
  InsertOperationOnTimeProcessor -up-|> PrintOperationProcessor

  AddLayerPlanTravelMovesProcessor *-- "*" TravelMoveGenerator
  abstract TravelMoveGenerator
  DirectTravelMoveGenerator -up-|> TravelMoveGenerator
  CombingTravelMoveGenerator -up-|> TravelMoveGenerator

  BedAdhesionConstraintsGenerator -up-|> FeatureExtrusionsConstraintsGenerator
  MeshFeaturesConstraintsGenerator -up-|> FeatureExtrusionsConstraintsGenerator

  MonotonicConstraintsGenerator -up-|> MoveSequencesConstraintsGenerator

  ExtruderPlanScheduler -up-|> PrintOperationProcessor
  class FeatureExtrusionScheduler
  ExtruderPlanScheduler *-- "*" FeatureExtrusionScheduler
  FeatureExtrusionScheduler *-- "*" FeatureExtrusionsConstraintsGenerator
  FeatureExtrusionScheduler *-- "*" MoveSequencesConstraintsGenerator

  SplitterProcessor *-- "*" PathSplitter

  abstract PathSplitter
  GradualFlowSplitter -up-|> PathSplitter
  ScarfSeamSplitter -up-|> PathSplitter
  SmoothSpeedSplitter -up-|> PathSplitter

  class InsertOperationOnTimeProcessor #paleturquoise
  class NozzleTemperatureCommandsProcessor #paleturquoise
  class BedTemperatureCommandsProcessor #paleturquoise
  class CoolingFanCommandsProcessor #paleturquoise
  class PrimeTowerProcessor #paleturquoise
  class CombingTravelMoveGenerator #paleturquoise
  class MinimumLayerTimeProcessor #paleturquoise
  class CoastingProcessor #paleturquoise
  class BackPressureCompensationProcessor #paleturquoise
  class SplitterProcessor #paleturquoise
  class PathSplitter #paleturquoise
  class GradualFlowSplitter #paleturquoise
  class ScarfSeamSplitter #paleturquoise
  class SmoothSpeedSplitter #paleturquoise
}
@enduml
