#!/usr/bin/env bash
# @generated by the agentic bootstrap. Regenerated on every run; the absence
# of this header is how the writer recognises a hand-written file and refuses
# to overwrite it. Edit the bootstrap, not this file.
set -euo pipefail

# Ensure target directories exist
mkdir -p .claude/hooks .opencode .agents/hooks .github/hooks   .agents/rules .claude/rules .opencode/rules   .agents/agents .claude/agents .opencode/agents .github/agents

# Clean up broken symlinks left by older bootstrap runs.
for mirror in .claude/rules .opencode/rules; do
  for link in "$mirror"/*; do
    if [ -L "$link" ] && [ ! -e "$link" ]; then
      rm -f "$link"
    fi
  done
done

# Claude Code reads hooks only from .claude/settings.json. A parallel
# .claude/hooks.json is never read and only invites drift — remove it.
rm -f .claude/hooks.json

# CLAUDE.md may be a symlink (Claude Code follows links); GEMINI.md must be a
# REAL generated file — Antigravity skips symlinks, and a whole rollout wave
# shipped no GEMINI.md at all.
if [ -f AGENTS.md ] && [ ! -L AGENTS.md ]; then
  if [ -L CLAUDE.md ]; then
    rm -f CLAUDE.md
  fi
  { echo "<!-- @generated from AGENTS.md. Edit AGENTS.md and re-run sync. -->"; cat AGENTS.md; } > CLAUDE.md
  rm -f GEMINI.md
  {
    echo "<!-- @generated from AGENTS.md by scripts/sync_agentic_configs.sh."
    echo "     Edit AGENTS.md and re-run the sync - do not edit this file. -->"
    echo ""
    cat AGENTS.md
  } > GEMINI.md
fi

# Mirror as regular files: Windows Git checkouts commonly disable symlinks.
# The source remains .agents/rules; sync is a compilation step, not authorship.
if [ -d .agents/rules ]; then
  for rulefile in .agents/rules/*.md; do
    if [ -f "$rulefile" ]; then
      base="$(basename "$rulefile")"
      rm -f ".claude/rules/$base" ".opencode/rules/$base"
      cp "$rulefile" ".claude/rules/$base"
      cp "$rulefile" ".opencode/rules/$base"
    fi
  done
  for mirror in .claude/rules .opencode/rules; do
    for mirrored in "$mirror"/*.md; do
      [ -e "$mirrored" ] || [ -L "$mirrored" ] || continue
      base="$(basename "$mirrored")"
      if [ "$base" = "agents.md" ]; then
        continue  # opencode's AGENTS.md pointer, managed below
      fi
      if [ ! -f ".agents/rules/$base" ]; then
        rm -f "$mirrored"
      fi
    done
  done
fi

# Mirror subagent definitions across platforms. Every charter under
# .agents/agents/ is mirrored — naming them individually is how the reviewer
# stayed the only agent the other three platforms could see.
for agent_dir in .agents/agents/*/; do
  [ -f "${agent_dir}agent.md" ] || continue
  agent_name=$(basename "$agent_dir")
  for platform in .claude .opencode .github; do
    rm -f "$platform/agents/${agent_name}.md"
    cp "${agent_dir}agent.md" "$platform/agents/${agent_name}.md"
  done
done

# Copy AGENTS.md for OpenCode rule discovery
if [ -f AGENTS.md ]; then
  rm -f .opencode/rules/agents.md
  cp AGENTS.md .opencode/rules/agents.md
fi

# Register the .talismanrc union merge driver for this clone. Best-effort:
# clones without it merge .talismanrc textually (rare after the threshold
# change shrank the churn surface). GitHub's server-side "mergeable" badge
# cannot see a repo-local driver — a CONFLICTING badge there is cosmetic.
if [ -f .agents/hooks/talisman_guard.py ]; then
  git config merge.talismanrc.driver "python3 .agents/hooks/talisman_guard.py merge %O %A %B" 2>/dev/null || true
fi

# Rebuild the Copilot rule index from .agents/rules/. Copilot learns which
# rules exist from that one link list; the bootstrap renders it from the rules
# a single run produced, so repo-owned and custom-band rules never reached it
# and no sync ever put them back.
if [ -d .agents/rules ] && [ -f .agents/hooks/copilot_index.py ]; then
  python3 .agents/hooks/copilot_index.py
fi

# Recompile AI exclusion targets from .aiignore (no platform reads it directly)
if [ -f .aiignore ] && [ -f .agents/hooks/compile_aiignore.py ]; then
  python3 .agents/hooks/compile_aiignore.py
fi

# Re-checksum drifted .talismanrc entries LAST, once every file this script can
# still rewrite has reached its final content. Adding a repo-owned rule changes
# .agents/rules-manifest.json, and without this the stale exemption blocked the
# next commit through the sanctioned tool. `refresh` never adds an entry, so a
# genuinely new finding still needs `allow` and a human.
if [ -f .agents/hooks/talisman_guard.py ] && [ -f .talismanrc ] \
   && command -v talisman >/dev/null 2>&1; then
  python3 .agents/hooks/talisman_guard.py refresh \
    || echo "WARNING: .talismanrc refresh incomplete (see above)." >&2
fi

echo "Synced Quad-Agent configurations and rule structures successfully."
