#!/usr/bin/env bash
# @generated by the agentic bootstrap. Regenerated on every run; the absence
# of this header is how the writer recognises a hand-written file and refuses
# to overwrite it. Edit the bootstrap, not this file.
set -euo pipefail

echo "==> Running Pre-PR Verification & Quality Gate Audit..."
if command -v pre-commit >/dev/null 2>&1; then
    # Verify THIS branch's diff, never the whole tree. On a brownfield
    # repository `--all-files` makes the whitespace/EOF fixers rewrite hundreds
    # of untouched files, and that churn then lands in the PR — the exact
    # failure `.agents/dispatch-invariants.md` forbids.
    BASE_BRANCH=$(python3 -c 'import json;print(json.load(open(".agents/bootstrap-profile.json")).get("base_branch","main"))' 2>/dev/null || echo main)
    BASE_REF="${BASE_REF:-origin/$BASE_BRANCH}"

    # Belt and braces for the scoping above. The fixers are restricted to
    # managed paths in `.pre-commit-config.yaml`, but this repository's own
    # config is user-editable and a hook added later may well rewrite files.
    # So: record the tree, run, and compare. Stop rather than automatically
    # reverting a contributor's work if a formatter touches an unrelated file.
    _pre_state=$(git status --porcelain 2>/dev/null || true)

    _precommit_rc=0
    pre-commit run --from-ref "$BASE_REF" --to-ref HEAD || _precommit_rc=$?

    _post_state=$(git status --porcelain 2>/dev/null || true)
    if [ "$_pre_state" != "$_post_state" ]; then
        # Which files the run itself touched, minus the ones this branch was
        # already changing (a fixer tidying your own edit is legitimate).
        _branch_files=$(git diff --name-only "$BASE_REF"...HEAD 2>/dev/null || true)
        _touched=$(comm -13 \
            <(printf '%s\n' "$_pre_state" | sed 's/^...//' | sort) \
            <(printf '%s\n' "$_post_state" | sed 's/^...//' | sort) || true)
        _churn=$(comm -23 \
            <(printf '%s\n' "$_touched" | grep -v '^$' | sort -u) \
            <(printf '%s\n' "$_branch_files" | grep -v '^$' | sort -u) || true)
        if [ -n "$_churn" ]; then
            echo "❌ pre-commit REWROTE files this branch does not change:"
            printf '    %s\n' $_churn
            echo "    Restore or inspect these files manually; this gate never"
            echo "    discards changes from the working tree."
            exit 1
        fi
    fi
    [ "$_precommit_rc" -eq 0 ] || { echo "❌ Pre-commit checks failed!"; exit 1; }
else
    echo "❌ ERROR: pre-commit is not installed! Install it with 'pip install pre-commit'."
    exit 1
fi

echo "==> Checking orientation docs are actually filled in..."
# One gate, every placeholder syntax: TODO(agent), raw double-brace tokens,
# TBD, <placeholder>. The old gate grepped only TODO(agent) and shipped a
# DESIGN.md whose unfilled token placeholders it could not see.
PLACEHOLDER_RE='TODO\(agent\)|\{\{[A-Z_]+\}\}|<placeholder|(^|[^A-Za-z])TBD([^A-Za-z]|$)'
for doc in AGENTS.md DESIGN.md GEMINI.md; do
    [ -f "$doc" ] || continue
    n=$(grep -cE "$PLACEHOLDER_RE" "$doc" || true)
    if [ "$n" -gt 0 ]; then
        echo "[X] $doc still has $n unfilled placeholder marker(s)."
        echo "    An orientation document full of placeholders is worse than none:"
        echo "    agents read it, learn nothing, and trust it anyway."
        echo "    Fill the sections from the repository before opening a PR:"
        grep -nE "$PLACEHOLDER_RE" "$doc" | head -10
        exit 1
    fi
done

if [ -f .agents/hooks/run_adversarial_audit.py ]; then
    python3 .agents/hooks/run_adversarial_audit.py || { echo "❌ Adversarial audit failed!"; exit 1; }
fi

# E2E browser-evidence gate — present only in cloud/frontend repositories (the
# registry writes the script there and nowhere else), so this `-f` guard makes
# it cloud-only without a second predicate. It reads the PR body via gh; before
# a PR exists it passes with an advisory note and enforces once the PR is open.
if [ -f .agents/hooks/check_e2e_evidence.py ]; then
    python3 .agents/hooks/check_e2e_evidence.py || { echo "❌ E2E browser verification evidence missing for user-facing cloud changes!"; exit 1; }
fi

# Fire-proofing: a hook you have not watched fire is unproven. Trigger each
# guard against a violating fixture; the PR's V&V table is generated from the
# recorded results, never typed by hand.
if [ -f .agents/hooks/verify_hooks_fire.py ]; then
    python3 .agents/hooks/verify_hooks_fire.py || { echo "❌ Fire-proofing failed: a wired guard did not block!"; exit 1; }
    echo "==> V&V table for the PR body (generated from recorded runs):"
    python3 .agents/hooks/verify_hooks_fire.py --vv-table
fi

# Register the .talismanrc union merge driver for this clone (idempotent).
if [ -f .agents/hooks/talisman_guard.py ]; then
    git config merge.talismanrc.driver "python3 .agents/hooks/talisman_guard.py merge %O %A %B" || true
fi

# Base-branch drift is the single most common source of a PR that opens
# already conflicting. The hook is advisory by design — it cannot know whether
# this repository integrates by merge or by rebase — so surface it here, where
# a PR is about to be opened, rather than leaving it installed and uncalled.
if [ -f .agents/hooks/check_upstream_alignment.py ]; then
    python3 .agents/hooks/check_upstream_alignment.py || true
fi

if [ -f .agents/hooks/check_security_downgrades.py ]; then
    python3 .agents/hooks/check_security_downgrades.py || {
        echo "❌ Security downgrade detected!"; exit 1; }
fi

echo "==> Verifying credential and environment file isolation..."
if git status --porcelain | awk '{print $2}' | grep -qE '^\.env$|^\.env\.local$'; then
    echo "❌ ERROR: Un-ignored or staged .env/.env.local file detected in git status!"
    echo "    Credentials must NEVER be staged or committed to git."
    exit 1
fi

echo "✅ All verification checks passed cleanly!"

# Locate the PR template. The bootstrap already resolved this — GitHub honours
# a repository-root and a docs/ template as well as .github/, and probing only
# .github/ here pointed agents at a template that was not the team's, exactly
# the shadowing this run's detector exists to prevent. Read the recorded answer
# first so the script and the detector cannot disagree.
PR_TEMPLATE=$(python3 -c \
    'import json;print(json.load(open(".agents/bootstrap-profile.json"))["pr_template"]["path"])' \
    2>/dev/null || true)
if [ -z "$PR_TEMPLATE" ] || [ ! -f "$PR_TEMPLATE" ]; then
    PR_TEMPLATE=""
    for cand in .github/PULL_REQUEST_TEMPLATE.md .github/pull_request_template.md \
                .github/workflows/PULL_REQUEST_TEMPLATE.md \
                PULL_REQUEST_TEMPLATE.md pull_request_template.md \
                docs/PULL_REQUEST_TEMPLATE.md docs/pull_request_template.md; do
        if [ -f "$cand" ]; then
            PR_TEMPLATE="$cand"
            break
        fi
    done
fi

if command -v gh >/dev/null 2>&1; then
    CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || true)
    if [ -n "$CURRENT_BRANCH" ]; then
        EXISTING_PR=$(gh pr list --head "$CURRENT_BRANCH" --json number --jq '.[0].number' 2>/dev/null || true)
        if [ -n "$EXISTING_PR" ] && [ "$EXISTING_PR" != "null" ]; then
            echo "==> Active PR #${EXISTING_PR} detected for branch '${CURRENT_BRANCH}'."
            echo "    Ensure PR description covers: Why, What, How, Verification & Validation (V&V), and PR Checklist."
            echo "    To update existing PR description: gh pr edit ${EXISTING_PR} --body-file <file>"
        else
            echo "==> No active PR found for branch '${CURRENT_BRANCH}'."
            if [ -n "$PR_TEMPLATE" ]; then
                echo "    Use template at '${PR_TEMPLATE}' when opening Draft PR:"
                echo "    gh pr create --draft --template '${PR_TEMPLATE}'"
            else
                echo "    Open Draft PR with: gh pr create --draft"
            fi
        fi
    fi
fi
