//Copyright (c) 2017 Ultimaker B.V.
//CuraEngine is released under the terms of the AGPLv3 or higher.

#ifndef TOPSURFACE_H
#define TOPSURFACE_H

#include "utils/polygon.h" //For the polygon areas.
#include "sliceDataStorage.h" //For the input mesh.

namespace cura
{

class SliceMeshStorage;

class TopSurface
{
public:
    /*!
     * Create an empty top surface area.
     */
    TopSurface();

    /*!
     * \brief Generate new top surface for a specific layer of a mesh.
     *
     * The surface will be generated by subtracting the 
     */
    TopSurface(SliceMeshStorage& mesh, size_t layer_number);

    /*!
     * \brief The areas of top surface, for each layer.
     */
    Polygons areas;
};

}

#endif /* TOPSURFACE_H */

